export type Source = { blob?: { id: string }; id: string; name: string; text: string; source_type: string };
export type Brand = { id: string; name: string; description: string; voice: string; approved_claims: string[]; forbidden_phrases: string[]; sources: Source[] };
export type Strategy = { positioning: string; core_message: string; audience_summary: string; content_pillars: string[]; assumptions: string[]; creative_directions: { id: string; name: string; description: string; rationale: string }[]; source_refs: string[] };
export type Media = { id: string; kind: string; mime_type: string; alt_text: string; voice?: string; script?: string };
export type TimelineItem = { id: string; day: number; stage: string; platform: string; asset_type: string; objective: string };
export type SectionReview = { section: "brief" | "strategy" | "direction" | "timeline" | "insights" | "learnings"; revision: number; decision: "approved" | "changes_requested"; feedback: string; created_at: string; user_id: string };
export type Version = { media?: Media; media_items?: Media[]; caption?: string; generation_prompt?: string; version: number; hook: string; body: string; cta: string; source_refs: string[]; evaluation: { passed: boolean; issues: string[]; checks: Record<string, boolean>; model?: string }; created_at: string };
export type Publication = { id: string; version: number; status: string; account_name: string; scheduled_at: string; run_at?: string; published_at?: string; url?: string; error?: string; post_ids: string[] };
export type SocialConnection = { id: string; brand_id: string; platform: string; display_name: string; provider_account_id: string; status: string; expires_at: string; scopes: string[] };
export type ConnectionResponse = { connections: SocialConnection[]; providers: { platform: string; configured: boolean; reason?: string }[] };
export type Asset = { publication?: Publication; publication_history?: Publication[]; timeline_item_id?: string; timeline_snapshot?: TimelineItem; id: string; campaign_id: string; platform: string; asset_type: string; status: string; current_version: number; versions: Version[]; approvals: { version: number; decision: string; feedback: string; created_at: string }[] };
export type Trace = { id: string; event_type: string; message: string; status: string; timestamp: string };
export type Campaign = { generation_prompts?: Record<string, string>; section_revisions?: Record<string, number>; reviews?: SectionReview[]; generation_mode?: string; insights?: string[]; id: string; brand_id: string; name: string; brief: string; goal: string; audience: string; platforms: string[]; duration_days: number; status: string; created_at: string; strategy: Strategy | null; selected_direction: string | null; timeline: TimelineItem[]; assets: Asset[]; trace: Trace[]; experiments: { id: string; name: string; asset_id: string; variable: string; variants: { review_asset_id?: string; evaluation?: Version["evaluation"]; label: string; hook: string; impressions: number; clicks: number; conversions: number }[]; is_demo: boolean }[]; learnings: { id: string; statement: string; evidence: string; confidence: number; saved_to_brand: boolean }[] };
export type Analytics = { metrics_source?: string; availability?: Record<string, boolean>; sync?: { captured_at: string; results: { asset_id: string; status: string; error?: string }[] }; likes?: number; comments?: number; reposts?: number; is_demo: boolean; impressions: number; clicks: number; conversions: number; ctr: number; platforms: { availability?: Record<string, boolean>; platform: string; impressions: number; clicks: number; conversions: number }[]; observations: string[] };

